### ISSUE TITLE
Global Rate Limit

### ISSUE THREAD

**Issue by svandragt** [kylemanna/docker-syncthing-relay#4]
Hello is there a way to set the global rate limit (strelaysrv 's [-global-rate=<bytes/s>]) when setting up the systemd server? 

I am happy to contribute a relay but I received note from my host I went through 1600GB of traffic  in the span of a few weeks, which means I had to stop the service  until my next billing period :)

**Comment by kylemanna** [comment]
You just need to pass the arguments to the docker image when you start it:

    docker run --rm --name my-syncthing-relay -p 22067:22067/tcp -p 22070:22070/tcp kylemanna/syncthing-relay strelaysrv -global-rate 5000000

**Comment by svandragt** [comment]
That works: syntax is -global-rate=5000000
For a good value see [this calculation](https://www.wolframalpha.com/input/?i=1000GB+in+bytes+%2F+1+month+in+seconds)
