### ISSUE TITLE
ENTRYPOINT vs CMD

### ISSUE THREAD

**Issue by maleadt** [kylemanna/docker-syncthing-relay#6]
(not entirely sure about the equivalence, hence an issue instead of a PR)

I'm using your container from docker compose, where it is convenient to be able to pass additional arguments using the [`command`](https://docs.docker.com/compose/compose-file/#command) option. If the container would specify `/usr/bin/strelaysrv` as the `ENTRYPOINT`, instead of the `CMD`, we wouldn't need to repeat the path to the binary in the `command` option.

For example, https://github.com/v2tec/watchtower, where you can just have `command: --interval 30` because the path to the binary is configured in the Dockerfile as `ENTRYPOINT ["/watchtower"]`.

**Comment by delfer** [comment]
@maleadt https://github.com/kylemanna/docker-syncthing-relay/pull/7
